# Generated by Django 2.1.1 on 2018-09-09 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20180908_0535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='date_time',
        ),
        migrations.AddField(
            model_name='post',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
