# Generated by Django 2.1.1 on 2018-09-10 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20180909_0109'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-title', '-date']},
        ),
    ]
